export type Chord = {
  category: string;
  label: string;
  abbr: string;
  value: string;
  keys: number[];
  keyNames: string[];
};

export const categories = [
  "major",
  "minor",
  "dominant",
  "symmetrical",
  "miscellaneous",
];

export const chords: Chord[] = [
  // Major
  {
    category: "major",
    label: "major",
    abbr: "major",
    value: "major",
    keys: [0, 4, 7],
    keyNames: ["Root", "Major third", "Perfect fifth"],
  },
  {
    category: "major",
    label: "major 7th",
    abbr: "major 7th",
    value: "major-seventh",
    keys: [0, 4, 7, 11],
    keyNames: ["Root", "Major third", "Perfect fifth", "Major seventh"],
  },
  {
    category: "major",
    label: "major 9th",
    abbr: "major 9th",
    value: "major-ninth",
    keys: [0, 4, 7, 11, 14],
    keyNames: [
      "Root",
      "Major third",
      "Perfect fifth",
      "Major seventh",
      "Major ninth",
    ],
  },
  {
    category: "major",
    label: "major 11th",
    abbr: "major 11th",
    value: "major-eleventh",
    keys: [0, 4, 7, 11, 14, 17],
    keyNames: [
      "Root",
      "Major third",
      "Perfect fifth",
      "Major seventh",
      "Major ninth",
      "Perfect eleventh",
    ],
  },
  {
    category: "major",
    label: "major 6th",
    abbr: "major 6th",
    value: "sixth",
    keys: [0, 4, 7, 9],
    keyNames: ["Root", "Major third", "Perfect fifth", "Major sixth"],
  },
  {
    category: "major",
    label: "6add9",
    abbr: "6/9",
    value: "six-add-nine",
    keys: [0, 4, 7, 9, 14],
    keyNames: [
      "Root",
      "Major third",
      "Perfect fifth",
      "Major sixth",
      "Major ninth",
    ],
  },

  // Minor
  {
    category: "minor",
    label: "minor",
    abbr: "minor",
    value: "minor",
    keys: [0, 3, 7],
    keyNames: ["Root", "Minor third", "Perfect fifth"],
  },
  {
    category: "minor",
    label: "minor 7th",
    abbr: "minor 7th",
    value: "minor-seventh",
    keys: [0, 3, 7, 10],
    keyNames: ["Root", "Minor third", "Perfect fifth", "Minor seventh"],
  },
  {
    category: "minor",
    label: "minor 9th",
    abbr: "minor 9th",
    value: "minor-ninth",
    keys: [0, 3, 7, 10, 14],
    keyNames: [
      "Root",
      "Minor third",
      "Perfect fifth",
      "Minor seventh",
      "Major ninth",
    ],
  },
  {
    category: "minor",
    label: "minor 11th",
    abbr: "minor 11th",
    value: "minor-eleventh",
    keys: [0, 3, 7, 10, 14, 17],
    keyNames: [
      "Root",
      "Minor third",
      "Perfect fifth",
      "Minor seventh",
      "Major ninth",
      "Perfect eleventh",
    ],
  },
  {
    category: "minor",
    label: "minor 6th",
    abbr: "minor 6th",
    value: "minor-sixth",
    keys: [0, 3, 7, 9],
    keyNames: ["Root", "Minor third", "Perfect fifth", "Major sixth"],
  },
  {
    category: "minor",
    label: "minor major 7th",
    abbr: "min (maj7)",
    value: "minor-major-seventh",
    keys: [0, 3, 7, 11],
    keyNames: ["Root", "Minor third", "Perfect fifth", "Major seventh"],
  },
  {
    category: "minor",
    label: "minor major 9th",
    abbr: "min (maj9)",
    value: "minor-major-ninth",
    keys: [0, 3, 7, 11, 14],
    keyNames: [
      "Root",
      "Minor third",
      "Perfect fifth",
      "Major seventh",
      "Major ninth",
    ],
  },
  {
    category: "minor",
    label: "minor major 11th",
    abbr: "min (maj11)",
    value: "minor-major-eleventh",
    keys: [0, 3, 7, 11, 14, 17],
    keyNames: [
      "Root",
      "Minor third",
      "Perfect fifth",
      "Major seventh",
      "Major ninth",
      "Perfect eleventh",
    ],
  },
  {
    category: "minor",
    label: "minor 7th♭5",
    abbr: "m7♭5",
    value: "minor-seventh-flat-five",
    keys: [0, 3, 6, 10],
    keyNames: [
      "Root",
      "Minor third",
      "Diminished fifth / Flat fifth",
      "Minor seventh",
    ],
  },
  {
    category: "minor",
    label: "minor 7th♭9",
    abbr: "m7♭9",
    value: "minor-seventh-flat-nine",
    keys: [0, 3, 7, 10, 13],
    keyNames: [
      "Root",
      "Minor third",
      "Perfect fifth",
      "Minor seventh",
      "Minor ninth",
    ],
  },
  {
    category: "minor",
    label: "minor 7th#9",
    abbr: "m7#9",
    value: "minor-seventh-sharp-nine",
    keys: [0, 3, 7, 10, 15],
    keyNames: [
      "Root",
      "Minor third",
      "Perfect fifth",
      "Minor seventh",
      "Augmented ninth / Sharp ninth",
    ],
  },
  {
    category: "minor",
    label: "minor 7th♭5♭9",
    abbr: "m7♭5♭9",
    value: "minor-seventh-flat-five-flat-nine",
    keys: [0, 3, 6, 10, 13],
    keyNames: [
      "Root",
      "Minor third",
      "Diminished fifth / Flat fifth",
      "Minor seventh",
      "Minor ninth / Flat ninth",
    ],
  },
  {
    category: "minor",
    label: "minor 7th♭5#9",
    abbr: "m7♭5#9",
    value: "minor-seventh-flat-five-sharp-nine",
    keys: [0, 3, 6, 10, 15],
    keyNames: [
      "Root",
      "Minor third",
      "Diminished fifth / Flat fifth",
      "Minor seventh",
      "Augmented ninth / Sharp ninth",
    ],
  },

  // Dominant
  {
    category: "dominant",
    label: "7th",
    abbr: "7th",
    value: "seventh",
    keys: [0, 4, 7, 10],
    keyNames: ["Root", "Major third", "Perfect fifth", "Minor seventh"],
  },
  {
    category: "dominant",
    label: "9th",
    abbr: "9th",
    value: "ninth",
    keys: [0, 4, 7, 10, 14],
    keyNames: [
      "Root",
      "Major third",
      "Perfect fifth",
      "Minor seventh",
      "Major ninth",
    ],
  },
  {
    category: "dominant",
    label: "11th",
    abbr: "11th",
    value: "eleventh",
    keys: [0, 4, 7, 10, 14, 17],
    keyNames: [
      "Root",
      "Major third",
      "Perfect fifth",
      "Minor seventh",
      "Major ninth",
      "Perfect eleventh",
    ],
  },
  {
    category: "dominant",
    label: "dominant 7th♭5",
    abbr: "7-5",
    value: "seven-flat-five",
    keys: [0, 4, 6, 10],
    keyNames: [
      "Root",
      "Major third",
      "Diminished fifth / Flat fifth",
      "Minor seventh",
    ],
  },
  {
    category: "dominant",
    label: "dominant 7th#5",
    abbr: "7+5",
    value: "seven-sharp-five",
    keys: [0, 4, 8, 10],
    keyNames: [
      "Root",
      "Major third",
      "Augmented fifth / Sharp fifth",
      "Minor seventh",
    ],
  },
  {
    category: "dominant",
    label: "dominant 7th♭9",
    abbr: "7-9",
    value: "seven-flat-nine",
    keys: [0, 4, 7, 10, 13],
    keyNames: [
      "Root",
      "Major third",
      "Perfect fifth",
      "Minor seventh",
      "Minor ninth / Flat ninth",
    ],
  },
  {
    category: "dominant",
    label: "dominant 7th#9",
    abbr: "7+9",
    value: "seven-sharp-nine",
    keys: [0, 4, 7, 10, 15],
    keyNames: [
      "Root",
      "Major third",
      "Perfect fifth",
      "Minor seventh",
      "Augmented ninth / Sharp ninth",
    ],
  },
  {
    category: "dominant",
    label: "dominant 7th♭5♭9",
    abbr: "7-5-9",
    value: "seven-flat-five-flat-nine",
    keys: [0, 4, 6, 10, 13],
    keyNames: [
      "Root",
      "Major third",
      "Diminished fifth / Flat fifth",
      "Minor seventh",
      "Minor ninth / Flat ninth",
    ],
  },
  {
    category: "dominant",
    label: "dominant 7th#5#9",
    abbr: "7+5+9",
    value: "seven-sharp-five-sharp-nine",
    keys: [0, 4, 8, 10, 15],
    keyNames: [
      "Root",
      "Major third",
      "Augmented fifth / Sharp fifth",
      "Minor seventh",
      "Augmented ninth / Sharp ninth",
    ],
  },
  {
    category: "dominant",
    label: "dominant 7th♭5#9",
    abbr: "7-5+9",
    value: "seven-flat-five-sharp-nine",
    keys: [0, 4, 6, 10, 15],
    keyNames: [
      "Root",
      "Major third",
      "Diminished fifth / Flat fifth",
      "Minor seventh",
      "Augmented ninth / Sharp ninth",
    ],
  },
  {
    category: "dominant",
    label: "dominant 7th#5♭9",
    abbr: "7+5-9",
    value: "seven-sharp-five-flat-nine",
    keys: [0, 4, 8, 10, 13],
    keyNames: [
      "Root",
      "Major third",
      "Augmented fifth / Sharp fifth",
      "Minor seventh",
      "Minor ninth / Flat ninth",
    ],
  },

  // Symmetrical
  {
    category: "symmetrical",
    label: "diminished",
    abbr: "dim",
    value: "diminished",
    keys: [0, 3, 6],
    keyNames: ["Root", "Minor third", "Diminished fifth / Flat fifth"],
  },
  {
    category: "symmetrical",
    label: "half-diminished",
    abbr: "half-dim",
    value: "half-diminished",
    keys: [0, 3, 6, 10],
    keyNames: [
      "Root",
      "Minor third",
      "Diminished fifth / Flat fifth",
      "Minor seventh",
    ],
  },
  {
    category: "symmetrical",
    label: "diminished 7th",
    abbr: "dim7",
    value: "diminished-seventh",
    keys: [0, 3, 6, 9],
    keyNames: ["Root", "Minor third", "Diminished fifth", "Diminished seventh"],
  },
  {
    category: "symmetrical",
    label: "augmented",
    abbr: "aug",
    value: "augmented",
    keys: [0, 4, 8],
    keyNames: ["Root", "Major third", "Augmented fifth"],
  },
  {
    category: "symmetrical",
    label: "augmented 7th",
    abbr: "aug7",
    value: "augmented-seventh",
    keys: [0, 4, 8, 10],
    keyNames: ["Root", "Major third", "Augmented fifth", "Major seventh"],
  },
  {
    category: "symmetrical",
    label: "augmented 9th",
    abbr: "aug9",
    value: "augmented-ninth",
    keys: [0, 4, 8, 10, 14],
    keyNames: [
      "Root",
      "Major third",
      "Augmented fifth",
      "Major seventh",
      "Major ninth",
    ],
  },
  {
    category: "symmetrical",
    label: "augmented 7th♭9",
    abbr: "aug7♭9",
    value: "augmented-seventh-flat-nine",
    keys: [0, 4, 8, 10, 13],
    keyNames: [
      "Root",
      "Major third",
      "Augmented fifth",
      "Major seventh",
      "Minor ninth / Flat ninth",
    ],
  },

  // Miscellaneous
  {
    category: "miscellaneous",
    label: "Root",
    abbr: "Root",
    value: "Root",
    keys: [0],
    keyNames: ["Root"],
  },
  {
    category: "miscellaneous",
    label: "5th (power-chord)",
    abbr: "5th",
    value: "fifth",
    keys: [0, 7],
    keyNames: ["Root", "Perfect fifth"],
  },
  {
    category: "miscellaneous",
    label: "♭5th",
    abbr: "♭5th",
    value: "flat-fifth",
    keys: [0, 6],
    keyNames: ["Root", "Diminished fifth / Flat fifth"],
  },
  {
    category: "miscellaneous",
    label: "add2",
    abbr: "add2",
    value: "add-two",
    keys: [0, 2, 4, 7],
    keyNames: ["Root", "Major second", "Major third", "Perfect fifth"],
  },
  {
    category: "miscellaneous",
    label: "add4",
    abbr: "add4",
    value: "add-four",
    keys: [0, 4, 5, 7],
    keyNames: ["Root", "Perfect fourth", "Major third", "Perfect fifth"],
  },
  {
    category: "miscellaneous",
    label: "add9",
    abbr: "add9",
    value: "add-nine",
    keys: [0, 4, 7, 14],
    keyNames: ["Root", "Major third", "Perfect fifth", "Major ninth"],
  },
  {
    category: "miscellaneous",
    label: "add11",
    abbr: "add11",
    value: "add-eleven",
    keys: [0, 4, 7, 17],
    keyNames: ["Root", "Major third", "Perfect fifth", "Perfect eleventh"],
  },
  {
    category: "miscellaneous",
    label: "suspended 2nd",
    abbr: "sus2",
    value: "suspended-second",
    keys: [0, 2, 7],
    keyNames: ["Root", "Major second", "Perfect fifth"],
  },
  {
    category: "miscellaneous",
    label: "suspended 4th",
    abbr: "sus4",
    value: "suspended-fourth",
    keys: [0, 5, 7],
    keyNames: ["Root", "Perfect fourth", "Perfect fifth"],
  },
  {
    category: "miscellaneous",
    label: "7th suspended 4th",
    abbr: "7sus4",
    value: "seventh-suspended-fourth",
    keys: [0, 5, 7, 10],
    keyNames: ["Root", "Perfect fourth", "Perfect fifth", "Minor seventh"],
  },
  {
    category: "miscellaneous",
    label: "9th suspended 4th",
    abbr: "9sus4",
    value: "ninth-suspended-fourth",
    keys: [0, 5, 7, 10, 14],
    keyNames: [
      "Root",
      "Perfect fourth",
      "Perfect fifth",
      "Minor seventh",
      "Major ninth",
    ],
  },
  {
    category: "miscellaneous",
    label: "11th suspended 4th",
    abbr: "11sus4",
    value: "eleventh-suspended-fourth",
    keys: [0, 5, 7, 10, 14, 17],
    keyNames: [
      "Root",
      "Perfect fourth",
      "Perfect fifth",
      "Minor seventh",
      "Major ninth",
      "Perfect eleventh",
    ],
  },
  {
    category: "miscellaneous",
    label: "minor add9",
    abbr: "madd9",
    value: "minor-add-nine",
    keys: [0, 3, 7, 14],
    keyNames: ["Root", "Minor third", "Perfect fifth", "Major ninth"],
  },
  {
    category: "miscellaneous",
    label: "minor add11",
    abbr: "madd11",
    value: "minor-add-eleven",
    keys: [0, 3, 7, 17],
    keyNames: ["Root", "Minor third", "Perfect fifth", "Perfect eleventh"],
  },
];
