export const Scales = [
  { label: "C", value: "c" },
  { label: "C#", value: "c-sharp" },
  { label: "D♭", value: "d-flat" },
  { label: "D", value: "d" },
  { label: "D#", value: "d-sharp" },
  { label: "E♭", value: "e-flat" },
  { label: "E", value: "e" },
  { label: "F", value: "f" },
  { label: "F#", value: "f-sharp" },
  { label: "G♭", value: "g-flat" },
  { label: "G", value: "g" },
  { label: "G#", value: "g-sharp" },
  { label: "A♭", value: "a-flat" },
  { label: "A", value: "a" },
  { label: "A#", value: "a-sharp" },
  { label: "B", value: "b" },
];
